//
// Created by Aldrin on 06-01-2024.
//

#ifndef DOOCS_MAXIMUMPROFITINJOBSCHEDULING_H
#define DOOCS_MAXIMUMPROFITINJOBSCHEDULING_H


class MaximumProfitInJobScheduling {

};


#endif //DOOCS_MAXIMUMPROFITINJOBSCHEDULING_H
