//
// Created by Aldrin on 04-01-2024.
//

#ifndef DOOCS_MINIMUMNOOFOPERATIONSTOMAKEARRAYEMPTY_H
#define DOOCS_MINIMUMNOOFOPERATIONSTOMAKEARRAYEMPTY_H


class MinimumNoOfOperationsToMakeArrayEmpty {

};


#endif //DOOCS_MINIMUMNOOFOPERATIONSTOMAKEARRAYEMPTY_H
